apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-fidznvey
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-fidznvey:ffd50ebdf61fdfd715710bcb6d78b3e96b7ef83d@sha256:d1b3ed26ac09f0cc6540bb0d55d99ea7259976250d440e535586e408a8c76136
          name: container-image
